# Site settings
title: SEWONIST = SEWON + ARTIST
email: sewonist@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Think of SEWONIST
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sewonist.github.io" # the base hostname & protocol for your site
address: "studio3O2, 210-20, Seongsan 1-dong, Mapo-gu, Seoul, Korea"
footer_links:
  dribbble: 
  email: sewonist@gmail.com
  facebook: phillip.ahn.58
  flickr: 
  github: sewonist
  instagram: 
  linkedin: 
  pinterest: sewonist
  rss: sewonist.github.io
  twitter: sewonist
  vimeo: sewonist
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
